### ISSUE TITLE
Bat failed to build

### ISSUE THREAD

**Issue by pyrsmk** [rust-onig/rust-onig#101]
Hi,

I was trying to install [bat](https://github.com/sharkdp/bat) with Cargo, but the building fails on : 

![Capture d’écran de 2019-03-21 15-07-27](https://user-images.githubusercontent.com/214497/54757873-62e3ba00-4beb-11e9-966f-8682a00eaeb6.png)

PS : I'm not a Rust developer

**Comment by iwillspeak** [comment]
Hi! Thanks for the issue and sorry for the late response.

What version of `rustc` are you using (can you show the result of `rustc --version`?

**Comment by pyrsmk** [comment]
No problem for the late response!

I'm using rustc `1.31.0`.

**Comment by iwillspeak** [comment]
Hi, do you know if you're using a stable version of the compiler or a nightly build? Do you have clippy installed and if so how did you install it?

**Comment by pyrsmk** [comment]
In fact, I'm running under Ubuntu 18.04. I installed cargo (which depends on rustc) with APT. So I think the versions are stable. I didn't installed clippy on my own, it installed itself when I run `cargo install bat`.

**Comment by iwillspeak** [comment]
Interesting. I think this is due to the exact version of the compiler being used. Looks like those style of lints were in a transition phase at that point. In older compilers we just get a warning that the lint isn't supported: https://travis-ci.org/rust-onig/rust-onig/jobs/492013033#L504. In later compilers clippy should handle the lint if it is installed.

We can silience this warning by enabling the experimental feature `tool_lints` (which is should be enabled by default I think in 1.31.0`). Not sure that would do much good in this case though.

When I try to build either `onig` or `bat` locally on 1.31.0 I don't see this error. Neither with or without the `clippy` component.

Thre's a few issues similar to this:

 * https://github.com/bodil/im-rs/issues/66
 * https://github.com/rust-lang/rust/issues/54406

Neither seem to give a good suggestion of a work around. Could you try updating to a later compiler and see if this goes away.

I'm not sure that the version of the compiler you're using really is `1.31.0`. Either that or `bat` is some older version of the code and this issue has somehow been worked around by the `bat` maintainers.

**Comment by pyrsmk** [comment]
Since packages on Ubuntu are rarely up-to-date I think we can ignore this issue. Moreover, I chose to forget about installing bat with cargo and I chose to install it with `dpkg` :smile: 

Anyway, thanks to have taken the time to dig in this! I think we can close thise.
