### ISSUE TITLE
`Regex.capture_names` method from 4.x is not present in master

### ISSUE THREAD

**Issue by a-rodin** [rust-onig/rust-onig#128]
Hi!

In versions 4.x there was method [Regex.capture_names](https://docs.rs/onig/4.3.3/onig/struct.Regex.html#method.capture_names). However, it is not present in the master branch.

Is there a recommended replacement for it?

**Comment by a-rodin** [comment]
I figured out that it is possible to use [foreach_name](https://docs.rs/onig/5.0.0/onig/struct.Regex.html#method.foreach_name) as a replacement.

**Comment by iwillspeak** [comment]
Hi. This was one of the breaking changes in the 4.x release. Due to the way the capture names iterator was implemented it relied on internal Oniguruma structures. This made it buggy and impossible to support between different Oniguruma versions.

You are correct that the same can be achieved by calling `foreach_name` And collecting into a `Vec` or similar.
