### ISSUE TITLE
?= +velookahead regex did not return intended result. 

### ISSUE THREAD

**Issue by vadhri** [rust-onig/rust-onig#138]
Hi. 
I am of opinion that +ve look ahead works in rust onig. 
I am trying the following piece of code which is supposed to be using the regex from the link below. 
https://regex101.com/r/wJUaal/1

        let re = Regex::new("(?=(\\+[-\\+]*\\+))").unwrap();
        let st = String::from("+---+---+--+");
        println!("String to match: {}", st);

        for ch in re.find_iter(&st) {
            print!("{:?} {}", ch, &st[ch.0..=ch.1+2]);
        }
        println!("");

**Result**

(0, 0) +--(4, 4) +--(8, 8) +--

**Issue**
The length of the find cannot be returned so i cannot clip the string. Can you please help me identify how can I get the three different strings as in the sample url above ?

**Comment by iwillspeak** [comment]
I think the way this works is that the lookahead doesn't actually match the characters. 

<img width="443" alt="Screenshot 2020-05-16 at 09 25 37" src="https://user-images.githubusercontent.com/1004401/82114909-658e6080-9757-11ea-9d88-7880b5d69c6f.png">

In that example the overall matches are also zero-length, but the inner capture group matches the whole lookahead.

You could try using the full `Regex::capturess` rather than just the `Regex::find` API if you want to keep using that regex. Another option would be to change the regex to be a plain match rather than a lookahead so you could get the full extent from the `Regex::find` API.
