### ISSUE TITLE
Failure with Valid Input

### ISSUE THREAD

**Issue by adamrodger** [rust-onig/rust-onig#171]
Regex matching can fail depending on the order of alternatives, for example:

```rust
use onig::Regex;

fn main() {
    let regex_string = "Greater|GreaterOrEqual";

    let re = Regex::new(regex_string).unwrap();

    println!("Regex: {regex_string}");
    check(&re, "Greater");
    check(&re, "GreaterOrEqual");
}

fn check(regex: &Regex, input: &str) {
    let matched = regex.is_match(input);
    println!("Input: {input} = {matched}");
}
```

This produces the output:

```
Regex: Greater|GreaterOrEqual
Input: Greater = true
Input: GreaterOrEqual = false
```

If you swap the regex around to the opposite order then it passes:

```
Regex: GreaterOrEqual|Greater
Input: Greater = true
Input: GreaterOrEqual = true
```

It seems that if one of the options is a prefix of another option then the match fails for the longer alternative.

**Comment by iwillspeak** [comment]
I can reproduce this:

```
use onig::Regex;

fn main() {
    test("Greater|GreaterOrEqual");
    test("GreaterOrEqual|Greater");
}

fn test(regex_string: &str) {
    let re = Regex::new(regex_string).unwrap();
    println!("Regex: {regex_string}");
    check(&re, "Greater");
    check(&re, "GreaterOrEqual");
}

fn check(regex: &Regex, input: &str) {
    let matched = regex.is_match(input);
    println!("Input: {input} = {matched}");
}
```

This seems to be caused by the way that `is_match` works. We first match the regex against the text, and then check
that the whole text was matched. In this case the order of the alternation changes what Oniguruma matches. If the
`GreaterOrEqual` is first then we match the longer item. if `Greater` is first then we only match that. This then means
that the expression hasn't matched the whole input text causing the behaviour you're seeing.

There's an option for `Oniguruma` which should allow us to force it to choose the longest match, but setting it either
with `(?L)` in the pattern or via `RegexOptions::::REGEX_OPTION_FIND_LONGEST` doesn't seem to affect the
outcome.
