### ISSUE TITLE
Latest onig-sys fails to build on Travis

### ISSUE THREAD

**Issue by trishume** [rust-onig/rust-onig#42]
See https://travis-ci.org/trishume/syntect/builds/250590654 for the build log.

It's mostly a bunch of errors like this:
```
Scanning dependencies of target onig
[  2%] [  4%] Building C object CMakeFiles/onig.dir/src/regerror.c.o
[  6%] [  8%] Building C object CMakeFiles/onig.dir/src/regparse.c.o
In file included from /usr/include/stdlib.h:320:0,
                 from /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/regint.h:144,
                 from /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/regerror.c:30:
/usr/include/x86_64-linux-gnu/sys/types.h:66:17: error: two or more data types in declaration specifiers
/usr/include/x86_64-linux-gnu/sys/types.h:81:17: error: two or more data types in declaration specifiers
```

@iwillspeak

**Comment by iwillspeak** [comment]
Thanks. This looks like it's caused by the upgrade to oniguruma 6.4.0. I'll investigate.

**Comment by iwillspeak** [comment]
It looks like [the Docs.rs build](https://docs.rs/crate/onig/1.4.0/builds/64119) fails with the same error.

**Comment by iwillspeak** [comment]
Frustratingly this doesn't fail on our own Travis build and I can't get it to fail locally. Even more frustratingly my charger has just given up and I'm out of battery. I think the commit which caused the issue is from [b350d3](https://github.com/kkos/oniguruma/commit/b350d3b54a83e4adad9ddccd1dbbb4681704cde6). For some reason the header guards mustn't be interpreted properly and `inttypes.h` is being included twice.

**Comment by codeyash** [comment]
Linux Mint 18

rustc 1.20.0-nightly (05b579766 2017-07-01)
binary: rustc
commit-hash: 05b5797664d6aeaa0c7d0606610f336fe0b57e97
commit-date: 2017-07-01
host: x86_64-unknown-linux-gnu
release: 1.20.0-nightly
LLVM version: 4.0

**Comment by iwillspeak** [comment]
I have now managed to reproduce this issue on a VM. Building onig from source, which itself compiles onig_sys, is fine. Building from the version downloaded from Crates.io fails. Looking at the version of oniguruma that exists in the Crates.io version I can't get it to build. Guessing it must have got corrupted somehow. It was uploaded on a particularly flaky Cornish internet connection.

I'll try re-publishing as 64.0.1 and see how that affects things.

**Comment by codeyash** [comment]
Okay. I will wait.

**Comment by iwillspeak** [comment]
A test build locally of trishume/syntect builds now against onig 1.4.1. It's the same source as 1.4.0, just re-uploaded. Not sure what went wrong.

Let me know if this fixes things @codeyash, @trishume. If not I'll re-open this issue.

**Comment by trishume** [comment]
@iwillspeak thanks! syntect's Travis build is working again!

That's super weird about re-uploading the same source and it working, maybe crates.io doesn't have checksums when it really should?

**Comment by iwillspeak** [comment]
I guess so. I wondered if somehow or other it had uploaded a dirty version of the oniguruma source. I don't think that was the case though because I found what cargo had downloaded, cleaned it and still couldn't get it to build 😕 .

**Comment by codeyash** [comment]
git clone
    git pull

    https://pastebin.com/raw/KqMP5zRU

Facing again. Please suggest

**Comment by iwillspeak** [comment]
Hi @codeyash!

It looks like the problem you're having is different from the one discussed in this issue. In fact it looks to be a duplicate of #43. 

The crate in this repository provides a wrapper around an underlying C library. In some cases that library is compiled from source and linked into your program for you  as part of the `onig_sys` crate build. Rather than having a copy of the source of Oniguruma in this repository and having to keep it in sync we use a Git feature called *submodules*. Git submodules allow us to say 'take the contents of this other repository and put it in this folder'. By default just running `git clone` won't clone those submodules for you. You can force it to do so by running `git submodule init --update`. Rather than having to run this after each clone you can also run `git clone --recursive https://github.com/rust-onig/rust-onig`.

For more information about submodules you can take a look at [the Git Book](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

If you have any more questions about getting this crate to build after a clean checkout please raise them on #43.
