### ISSUE TITLE
cargo doc fails on onig_sys.

### ISSUE THREAD

**Issue by paul-tcell** [rust-onig/rust-onig#69]
Rust version 1.22.1 and 1.23.0.    The lines that have the language specifier after the 3 accent graves appear to be the problem.

```
error: unknown start of token: `
 --> <stdin>:1:1
  |
1 | ```c
  | ^
  |
help: unicode character '`' (Grave Accent) looks like ''' (Single Quote), but it's not
 --> <stdin>:1:1
  |
1 | ```c
  | ^

error: Could not document `onig_sys`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name onig_sys /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-65.0.1/src/lib.rs -o /Users/paul/dev/x/target/doc --cfg feature="static_onig" -L dependency=/Users/paul/dev/x/target/debug/deps --extern libc=/Users/paul/dev/x/target/debug/deps/liblibc-37eea92b7cbeea63.rlib` (exit code: 101)

```

**Comment by paul-tcell** [comment]
seems to work on the latest

**Comment by iwillspeak** [comment]
Hi, Thanks for the issue. I have seen something like this before. It is because of the documentation for the C bindings.

The difference between 3.0.1 from Crates and the version here on GitHub might be due to the new development on `master` preparing for the Oniguruma 6.7.0 release. When this is finalised the main crate version number will be bumped and a new version pused to Crates.
