### ISSUE TITLE
Regression: Memory leak introduced somewhere from 3.0.1 to 3.2.1

### ISSUE THREAD

**Issue by saarw** [rust-onig/rust-onig#84]
We noticed that oniguruma started leaking memory when upgrading from rust-onig 3.0.1 to 3.2.1. It's highly probable that this memory leak is somewhere in the underlying C library, can someone help verify that and post an issue for that project?

I have created a reproducer here that will grow the heap indefinitely (it goes away when I port back to search_with_options in 3.0.1) 
https://github.com/saarw/onig_leak

**Comment by iwillspeak** [comment]
Thanks for the issue. I'll look into this as soon as possible.

**Comment by iwillspeak** [comment]
According to Leaks these are created by `onig_new_match_param`. Presumably at [`MatchParam::default`](https://github.com/rust-onig/rust-onig/blob/master/src/match_param.rs#L39).

**Comment by iwillspeak** [comment]
Looks like by calling [`mem::transmute`](https://doc.rust-lang.org/std/mem/fn.transmute.html) in [`search_with_param`](https://github.com/rust-onig/rust-onig/blob/master/src/lib.rs#L703) it prevents the `Drop` impl being invoked. Guessing we should fix this by adding an `as_raw` method to expose the raw pointer rather than using `mem::transmute`.
